using FFXIVVoicePackCreator.VoiceSorting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RoleplayingVoiceDalamud {
    public static class RacialEmoteTime {
        public static List<TimeCodeData> TimeCodes() {
            var list = new List<TimeCodeData>();
            var timeCode = new TimeCodeData() { Descriptor = 0 + "_Masculine", };
            timeCode.TimeCodes.Add(0.03m);
            timeCode.TimeCodes.Add(0.08m);
            timeCode.TimeCodes.Add(0.05m);
            timeCode.TimeCodes.Add(0.13m);
            timeCode.TimeCodes.Add(7.67m);
            timeCode.TimeCodes.Add(0.20m);
            timeCode.TimeCodes.Add(0.20m);
            timeCode.TimeCodes.Add(0.01m);
            timeCode.TimeCodes.Add(0.18m);
            timeCode.TimeCodes.Add(0.08m);
            timeCode.TimeCodes.Add(0.21m);
            timeCode.TimeCodes.Add(0.30m);
            timeCode.TimeCodes.Add(0.12m);
            timeCode.TimeCodes.Add(0.56m);
            timeCode.TimeCodes.Add(0.15m);
            timeCode.TimeCodes.Add(0.24m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 0 + "_Feminine", };
            timeCode.TimeCodes.Add(0.10m);
            timeCode.TimeCodes.Add(0.30m);
            timeCode.TimeCodes.Add(0.17m);
            timeCode.TimeCodes.Add(0.15m);
            timeCode.TimeCodes.Add(5.53m);
            timeCode.TimeCodes.Add(0.37m);
            timeCode.TimeCodes.Add(0.12m);
            timeCode.TimeCodes.Add(0.28m);
            timeCode.TimeCodes.Add(0.31m);
            timeCode.TimeCodes.Add(0.19m);
            timeCode.TimeCodes.Add(0.26m);
            timeCode.TimeCodes.Add(0.27m);
            timeCode.TimeCodes.Add(0.08m);
            timeCode.TimeCodes.Add(0.59m);
            timeCode.TimeCodes.Add(0.24m);
            timeCode.TimeCodes.Add(0.07m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 1 + "_Masculine", };
            timeCode.TimeCodes.Add(0.10m);
            timeCode.TimeCodes.Add(1.50m);
            timeCode.TimeCodes.Add(0.77m);
            timeCode.TimeCodes.Add(0.24m);
            timeCode.TimeCodes.Add(4.68m);
            timeCode.TimeCodes.Add(0.78m);
            timeCode.TimeCodes.Add(0.38m);
            timeCode.TimeCodes.Add(0.43m);
            timeCode.TimeCodes.Add(0.40m);
            timeCode.TimeCodes.Add(0.07m);
            timeCode.TimeCodes.Add(0.29m);
            timeCode.TimeCodes.Add(1.00m);
            timeCode.TimeCodes.Add(0.17m);
            timeCode.TimeCodes.Add(0.87m);
            timeCode.TimeCodes.Add(0.20m);
            timeCode.TimeCodes.Add(0.25m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 1 + "_Feminine", };
            timeCode.TimeCodes.Add(1.15m);
            timeCode.TimeCodes.Add(0.44m);
            timeCode.TimeCodes.Add(0.04m);
            timeCode.TimeCodes.Add(0.37m);
            timeCode.TimeCodes.Add(6.47m);
            timeCode.TimeCodes.Add(0.41m);
            timeCode.TimeCodes.Add(0.38m);
            timeCode.TimeCodes.Add(0.29m);
            timeCode.TimeCodes.Add(0.61m);
            timeCode.TimeCodes.Add(0.20m);
            timeCode.TimeCodes.Add(0.16m);
            timeCode.TimeCodes.Add(0.26m);
            timeCode.TimeCodes.Add(0.18m);
            timeCode.TimeCodes.Add(0.04m);
            timeCode.TimeCodes.Add(0.27m);
            timeCode.TimeCodes.Add(0.12m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 2 + "_Masculine", };
            timeCode.TimeCodes.Add(0.21m);
            timeCode.TimeCodes.Add(0.13m);
            timeCode.TimeCodes.Add(0.48m);
            timeCode.TimeCodes.Add(0.28m);
            timeCode.TimeCodes.Add(4.96m);
            timeCode.TimeCodes.Add(0.20m);
            timeCode.TimeCodes.Add(0.20m);
            timeCode.TimeCodes.Add(0.16m);
            timeCode.TimeCodes.Add(0.07m);
            timeCode.TimeCodes.Add(0.16m);
            timeCode.TimeCodes.Add(0.30m);
            timeCode.TimeCodes.Add(0.10m);
            timeCode.TimeCodes.Add(0.13m);
            timeCode.TimeCodes.Add(0.83m);
            timeCode.TimeCodes.Add(0.21m);
            timeCode.TimeCodes.Add(0.05m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 2 + "_Feminine", };
            timeCode.TimeCodes.Add(0.06m);
            timeCode.TimeCodes.Add(0.30m);
            timeCode.TimeCodes.Add(0.16m);
            timeCode.TimeCodes.Add(0.60m);
            timeCode.TimeCodes.Add(6.57m);
            timeCode.TimeCodes.Add(0.67m);
            timeCode.TimeCodes.Add(0.43m);
            timeCode.TimeCodes.Add(0.37m);
            timeCode.TimeCodes.Add(0.60m);
            timeCode.TimeCodes.Add(0.30m);
            timeCode.TimeCodes.Add(0.93m);
            timeCode.TimeCodes.Add(1.03m);
            timeCode.TimeCodes.Add(0.21m);
            timeCode.TimeCodes.Add(0.70m);
            timeCode.TimeCodes.Add(0.23m);
            timeCode.TimeCodes.Add(0.26m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 3 + "_Masculine", };
            timeCode.TimeCodes.Add(0.06m);
            timeCode.TimeCodes.Add(0.10m);
            timeCode.TimeCodes.Add(0.10m);
            timeCode.TimeCodes.Add(0.10m);
            timeCode.TimeCodes.Add(7.97m);
            timeCode.TimeCodes.Add(0.33m);
            timeCode.TimeCodes.Add(0.16m);
            timeCode.TimeCodes.Add(0.20m);
            timeCode.TimeCodes.Add(0.50m);
            timeCode.TimeCodes.Add(0.17m);
            timeCode.TimeCodes.Add(0.34m);
            timeCode.TimeCodes.Add(1.12m);
            timeCode.TimeCodes.Add(0.09m);
            timeCode.TimeCodes.Add(0.20m);
            timeCode.TimeCodes.Add(0.26m);
            timeCode.TimeCodes.Add(0.26m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 3 + "_Feminine", };
            timeCode.TimeCodes.Add(0.18m);
            timeCode.TimeCodes.Add(0.08m);
            timeCode.TimeCodes.Add(0.22m);
            timeCode.TimeCodes.Add(0.28m);
            timeCode.TimeCodes.Add(7.97m);
            timeCode.TimeCodes.Add(0.10m);
            timeCode.TimeCodes.Add(0.29m);
            timeCode.TimeCodes.Add(0.05m);
            timeCode.TimeCodes.Add(0.24m);
            timeCode.TimeCodes.Add(0.34m);
            timeCode.TimeCodes.Add(0.34m);
            timeCode.TimeCodes.Add(0.08m);
            timeCode.TimeCodes.Add(0.07m);
            timeCode.TimeCodes.Add(0.36m);
            timeCode.TimeCodes.Add(0.35m);
            timeCode.TimeCodes.Add(0.32m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 4 + "_Masculine", };
            timeCode.TimeCodes.Add(0.14m);
            timeCode.TimeCodes.Add(0.10m);
            timeCode.TimeCodes.Add(0.12m);
            timeCode.TimeCodes.Add(0.30m);
            timeCode.TimeCodes.Add(6.41m);
            timeCode.TimeCodes.Add(0.50m);
            timeCode.TimeCodes.Add(0.50m);
            timeCode.TimeCodes.Add(0.16m);
            timeCode.TimeCodes.Add(0.28m);
            timeCode.TimeCodes.Add(0.06m);
            timeCode.TimeCodes.Add(0.69m);
            timeCode.TimeCodes.Add(0.36m);
            timeCode.TimeCodes.Add(0.44m);
            timeCode.TimeCodes.Add(0.02m);
            timeCode.TimeCodes.Add(0.18m);
            timeCode.TimeCodes.Add(0.30m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 4 + "_Feminine", };
            timeCode.TimeCodes.Add(0.07m);
            timeCode.TimeCodes.Add(0.24m);
            timeCode.TimeCodes.Add(0.14m);
            timeCode.TimeCodes.Add(2.00m);
            timeCode.TimeCodes.Add(6.93m);
            timeCode.TimeCodes.Add(0.14m);
            timeCode.TimeCodes.Add(0.09m);
            timeCode.TimeCodes.Add(0.00m);
            timeCode.TimeCodes.Add(0.37m);
            timeCode.TimeCodes.Add(0.05m);
            timeCode.TimeCodes.Add(0.13m);
            timeCode.TimeCodes.Add(0.30m);
            timeCode.TimeCodes.Add(0.09m);
            timeCode.TimeCodes.Add(0.59m);
            timeCode.TimeCodes.Add(0.21m);
            timeCode.TimeCodes.Add(0.31m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 5 + "_Masculine", };
            timeCode.TimeCodes.Add(0.26m);
            timeCode.TimeCodes.Add(0.10m);
            timeCode.TimeCodes.Add(0.10m);
            timeCode.TimeCodes.Add(0.07m);
            timeCode.TimeCodes.Add(4.17m);
            timeCode.TimeCodes.Add(0.69m);
            timeCode.TimeCodes.Add(0.32m);
            timeCode.TimeCodes.Add(0.19m);
            timeCode.TimeCodes.Add(0.19m);
            timeCode.TimeCodes.Add(0.19m);
            timeCode.TimeCodes.Add(0.59m);
            timeCode.TimeCodes.Add(0.19m);
            timeCode.TimeCodes.Add(0.22m);
            timeCode.TimeCodes.Add(0.45m);
            timeCode.TimeCodes.Add(0.73m);
            timeCode.TimeCodes.Add(0.61m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 5 + "_Feminine", };
            timeCode.TimeCodes.Add(0.20m);
            timeCode.TimeCodes.Add(0.15m);
            timeCode.TimeCodes.Add(0.40m);
            timeCode.TimeCodes.Add(0.27m);
            timeCode.TimeCodes.Add(5.72m);
            timeCode.TimeCodes.Add(0.07m);
            timeCode.TimeCodes.Add(0.27m);
            timeCode.TimeCodes.Add(0.30m);
            timeCode.TimeCodes.Add(0.67m);
            timeCode.TimeCodes.Add(0.05m);
            timeCode.TimeCodes.Add(0.43m);
            timeCode.TimeCodes.Add(0.26m);
            timeCode.TimeCodes.Add(0.23m);
            timeCode.TimeCodes.Add(0.63m);
            timeCode.TimeCodes.Add(0.17m);
            timeCode.TimeCodes.Add(0.14m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 6 + "_Masculine", };
            timeCode.TimeCodes.Add(0.60m);
            timeCode.TimeCodes.Add(0.44m);
            timeCode.TimeCodes.Add(0.79m);
            timeCode.TimeCodes.Add(0.52m);
            timeCode.TimeCodes.Add(1.09m);
            timeCode.TimeCodes.Add(0.64m);
            timeCode.TimeCodes.Add(1.17m);
            timeCode.TimeCodes.Add(1.29m);
            timeCode.TimeCodes.Add(0.44m);
            timeCode.TimeCodes.Add(1.03m);
            timeCode.TimeCodes.Add(1.98m);
            timeCode.TimeCodes.Add(1.31m);
            timeCode.TimeCodes.Add(0.85m);
            timeCode.TimeCodes.Add(0.76m);
            timeCode.TimeCodes.Add(0.67m);
            timeCode.TimeCodes.Add(0.61m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 6 + "_Feminine", };
            timeCode.TimeCodes.Add(0.77m);
            timeCode.TimeCodes.Add(1.37m);
            timeCode.TimeCodes.Add(2.86m);
            timeCode.TimeCodes.Add(0.89m);
            timeCode.TimeCodes.Add(6.80m);
            timeCode.TimeCodes.Add(0.88m);
            timeCode.TimeCodes.Add(1.15m);
            timeCode.TimeCodes.Add(0.59m);
            timeCode.TimeCodes.Add(0.61m);
            timeCode.TimeCodes.Add(0.96m);
            timeCode.TimeCodes.Add(0.73m);
            timeCode.TimeCodes.Add(1.08m);
            timeCode.TimeCodes.Add(1.14m);
            timeCode.TimeCodes.Add(0.69m);
            timeCode.TimeCodes.Add(0.03m);
            timeCode.TimeCodes.Add(0.03m);
            list.Add(timeCode);

            //Hrothgat
            timeCode = new TimeCodeData() { Descriptor = 7 + "_Masculine", };
            timeCode.TimeCodes.Add(0.56m);
            timeCode.TimeCodes.Add(0.41m);
            timeCode.TimeCodes.Add(0.62m);
            timeCode.TimeCodes.Add(0.98m);
            timeCode.TimeCodes.Add(6.00m);
            timeCode.TimeCodes.Add(0.98m);
            timeCode.TimeCodes.Add(0.90m);
            timeCode.TimeCodes.Add(0.73m);
            timeCode.TimeCodes.Add(0.77m);
            timeCode.TimeCodes.Add(1.26m);
            timeCode.TimeCodes.Add(0.90m);
            timeCode.TimeCodes.Add(0.90m);
            timeCode.TimeCodes.Add(0.59m);
            timeCode.TimeCodes.Add(0.70m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 7 + "_Feminine", };
            timeCode.TimeCodes.Add(0.56m);
            timeCode.TimeCodes.Add(0.41m);
            timeCode.TimeCodes.Add(0.62m);
            timeCode.TimeCodes.Add(0.98m);
            timeCode.TimeCodes.Add(6.00m);
            timeCode.TimeCodes.Add(0.98m);
            timeCode.TimeCodes.Add(0.90m);
            timeCode.TimeCodes.Add(0.73m);
            timeCode.TimeCodes.Add(0.77m);
            timeCode.TimeCodes.Add(1.26m);
            timeCode.TimeCodes.Add(0.90m);
            timeCode.TimeCodes.Add(0.90m);
            timeCode.TimeCodes.Add(0.59m);
            timeCode.TimeCodes.Add(0.70m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 8 + "_Masculine", };
            timeCode.TimeCodes.Add(0.51m);
            timeCode.TimeCodes.Add(0.93m);
            timeCode.TimeCodes.Add(1.19m);
            timeCode.TimeCodes.Add(0.81m);
            timeCode.TimeCodes.Add(6.00m);
            timeCode.TimeCodes.Add(0.83m);
            timeCode.TimeCodes.Add(0.46m);
            timeCode.TimeCodes.Add(0.56m);
            timeCode.TimeCodes.Add(0.82m);
            timeCode.TimeCodes.Add(0.69m);
            timeCode.TimeCodes.Add(1.27m);
            timeCode.TimeCodes.Add(1.21m);
            timeCode.TimeCodes.Add(0.74m);
            timeCode.TimeCodes.Add(0.88m);
            list.Add(timeCode);

            timeCode = new TimeCodeData() { Descriptor = 8 + "_Feminine", };
            timeCode.TimeCodes.Add(0.49m);
            timeCode.TimeCodes.Add(1.05m);
            timeCode.TimeCodes.Add(0.76m);
            timeCode.TimeCodes.Add(0.94m);
            timeCode.TimeCodes.Add(6.20m);
            timeCode.TimeCodes.Add(0.50m);
            timeCode.TimeCodes.Add(0.92m);
            timeCode.TimeCodes.Add(1.10m);
            timeCode.TimeCodes.Add(0.93m);
            timeCode.TimeCodes.Add(1.06m);
            timeCode.TimeCodes.Add(1.23m);
            timeCode.TimeCodes.Add(1.00m);
            timeCode.TimeCodes.Add(1.42m);
            timeCode.TimeCodes.Add(0.72m);
            list.Add(timeCode);
            return list;
        }
    }
}
