using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RoleplayingVoiceDalamud.Voice {
    public class NPCVoiceConfiguration {
        private Dictionary<string, string> _characterToVoiceList;
        private Dictionary<string, List<string>> _nameAndAliasesList;
        private List<KeyValuePair<string, string>> _extrasVoiceList;
        private List<KeyValuePair<string, bool>> _echoValuesList;
        private List<KeyValuePair<string, float>> _pitchValuesList;

        public NPCVoiceConfiguration() {
            _nameAndAliasesList = new Dictionary<string, List<string>> {
                { "Ungust", new List<string>() { "Obnoxious Merchant" } },
                { "2B", new List<string>() { "Woman in White", "Android in Black" } },
                { "Alpinaud", new List<string>() { "Self-assured Youth" } },
                { "Alisaie", new List<string>() { "Cynical Girl" } },
                { "Yda", new List<string>() { "Animated Pugilist" } },
                { "Papalymo", new List<string>() { "Short-tempered Thaumaturge" } },
                { "Anogg", new List<string>() { "Dwarf Facsimile" } },
                { "Machine Lifeform", new List<string>() { "Mysterious Machina" } },
                { "Llymlaen", new List<string>() { "Audacious Woman" } },
                { "Thaliak", new List<string>() { "Sagely Man" } },
                { "Azeyma", new List<string>() { "Spirited Woman's Voice", "Meerkat with Azeyma's Voice" } },
                { "Rhalgr", new List<string>() { "Sagely Man's Voice", "Hawk with Rhalgr's Voice" } },
                { "Nald'thal", new List<string>() { "Measured Mens Voice" } },
                { "Nophica", new List<string>() { "Cheery" } },
                { "Krile", new List<string>() { "Omphalos Monument" } }
            };

            _characterToVoiceList = new Dictionary<string, string> {
                { "Alphinaud", "Alev" },
                { "Self-assured Youth", "Alev" },
                { "Alisaie", "Alilev" },
                { "Cynical Girl", "Alilev" },
                { "Haurchefant", "HFort" },
                { "Artoirel", "Afort" },
                { "Charibert", "Cbert" },
                { "Hilda", "Hda" },
                { "Honoroit", "Hroit" },
                { "Ilberd", "Ird" },
                { "Alpha", "Kop" },
                { "King Thordan", "thord" },
                { "Y'shtola", "Yrhul" },
                { "Cultured Conjurer", "Yrhul" },
                { "Thancred", "Twaters" },
                { "Charming Thaumaturge", "Twaters" },
                { "Tataru", "Taru" },
                { "Yda", "Lhext" },
                { "Lyse", "Lhext" },
                { "Animated Pugilist", "Lhext" },
                { "Urianger", "Uauger" },
                { "Masked Man", "Uauger" },
                { "G'raha", "Gia" },
                { "Crystal Exarch", "Gia" },
                { "Minfilia", "Mward" },
                { "Ryne", "Mward" },
                { "Kokkol Dankkol", "Kool" },
                { "Papalymo", "Ptotol" },
                { "Short-tempered Thaumaturge", "Ptotol" },
                { "Krile", "Kmayerbal" },
                { "Matoya", "Moya" },
                { "Hydaelyn", "Hyn" },
                { "Kan-E-Senna", "Kes" },
                { "Merlwyb", "Mbloe" },
                { "Nanamo Ul Namo", "Nulnamo" },
                { "Lilira", "Nulnamo" },
                { "Aymeric", "Adeborel" },
                { "Lucia", "Lcia" },
                { "Taciturn Temple Knight", "Lcia" },
                { "Raubahn", "Rahn" },
                { "Pipin", "Pin" },
                { "Marques", "Cnangarl" },
                { "Cid", "Cnangarl" },
                { "Biggs", "Bman" },
                { "Airship Crewman", "Bman" },
                { "Wedge", "Wman" },
                { "Vidofnir", "Vnir" },
                { "House", "Hfk" },
                { "Warrior of Darkness", "ard" },
                { "Ardbert", "ard" },
                { "Arenvald", "Avald" },
                { "Azemi", "Azmi" },
                { "Bunchin", "Bchin" },
                { "Carvallain", "Cvain" },
                { "Cirina", "Cina" },
                { "Conrad", "Crad" },
                { "Curtis", "Ctis" },
                { "Grynewaht", "Gaht" },
                { "Gyoto", "Goto" },
                { "Hancock", "Hock" },
                { "Ikaruga", "Iruga" },
                { "Hien", "Hen" },
                { "Fordola", "Fola" },
                { "2B", "To be" },
                { "2P", "To be" },
                { "9S", "Nines" },
                { "Isse", "Isse" },
                { "Jifuya", "Juya" },
                { "Lakshmi", "Lhmi" },
                { "Lolorito", "Lito" },
                { "Magnai", "Mai" },
                { "Meffrid", "Mrid" },
                { "M'naago", "Mago" },
                { "Rasho", "Rho" },
                { "Sadu", "Su" },
                { "Shar", "Sar" },
                { "Soroban", "Sban" },
                { "Tansui", "Tui" },
                { "Temulun", "Tun" },
                { "Vira Battlemaid", "Vaid" },
                { "Tsukuyomi", "Tomi" },
                { "Katliss", "Kliss" },
                { "Theyler", "Ter" },
                { "Gaia", "irhm" },
                { "Emet-Selch", "Eselch" },
                { "Hades", "Eselch" },
                { "Almet", "Aet" },
                { "Beq Lugg", "Bug" },
                { "Bragi", "Bi" },
                { "Cassard", "Card" },
                { "Chai-Nuzz", "Cuz" },
                { "Dulia-Chai", "Dai" },
                { "Cymet", "Cet" },
                { "Feo Ul", "Ful" },
                { "Gynard", "Gard" },
                { "Gen Gen", "Geen" },
                { "Guthjon", "Gon" },
                { "Kai-Shirr", "Kir" },
                { "Lyna", "Lna" },
                { "Magnus", "Mus" },
                { "Seto", "So" },
                { "Sul Uin", "Sin" },
                { "Oul Sigun", "Sun" },
                { "Tesleen", "Ten" },
                { "Thaffe", "Tafe" },
                { "Theva", "Tva" },
                { "Uimet", "Uet" },
                { "Wrenden", "Wen" },
                { "Ys Iala", "Yala" },
                { "Hoary Boulder", "Hlder" },
                { "Erenvile", "Eille" },
                { "Fourchenault", "Fault" },
                { "Barnier", "Bier" },
                { "Montichaigne", "Montne" },
                { "Kytte", "Kte" },
                { "Varshahn", "Vahn" },
                { "Nidhana", "Nana" },
                { "Ahewann", "Aann" },
                { "Vrtra", "Vra" },
                { "A-Ruhn-Senna", "Aenna" },
                { "Sicard", "Sard" },
                { "Maxima", "Mima" },
                { "Jullus", "Jlus" },
                { "Quintus", "Qus" },
                { "Livingway", "Lway" },
                { "Mappingway", "Mway" },
                { "Growingway", "Gway" },
                { "Loporrit", "Lrit" },
                { "Matsya", "Mya" },
                { "Mehvan", "Mvan" },
                { "Elidibus", "Ebus" },
                { "Themis", "Ebus" },
                { "White-robed Ascian", "Ebus" },
                { "Hermes", "Hes" },
                { "Meteion", "Mion" },
                { "Hythlodaeus", "Hdaeus" },
                { "Venat", "Vnat" },
                { "Lahabrea", "Lbrea" },
                { "Galene", "Gene" },
                { "Wilfsunn", "Wun" },
                { "Bloewyda", "Byda" },
                { "Moenbryda", "Lhext" },
                { "Eya", "Eya" },
                { "Sir", "techBot" },
                { "Omega", "techBot" },
                { "M-017", "m7" },
                { "Zero", "Zo" },
                { "Wuk Lamat", "Wamat" },
                { "Fandaniel", "Fdaniel" },
                { "Asahi", "Fdaniel" },
                { "Midgardsormr", "Msrmr" },
                { "Worldly Affairs Official", "Wao" },
                { "Ameliance", "Aiance" },
                { "Moogle", "Kop" },
                { "Kuplo Kopp", "Kop" },
                { "Sula", "tf1" },
                { "Sevrin", "Sard" },
                { "Masked Mage", "Lbrea" },
                { "???", "Sys" },
                { "Ifrit", "Rava" },
                { "Varis zos Galvus", "Vzosgal" },
                { "Zenos", "Zyaegal" },
                { "Gaius", "Gvanbael" },
                { "Shadowhunter", "Gvanbael" },
                { "Menacing Mercenary", "Gvanbael" },
                { "Nero", "Ntolscae" },
                { "Runar", "Rar" },
                { "Estinien", "Ewyrm" },
                { "Ysayle", "Ydango" },
                { "Iceheart", "Ydango" },
                { "Count Edmont de Fortemps", "Edefort" },
                { "Emmanellain", "Emmdefort" },
                { "Yugiri", "Ymist" },
                { "Nabriales", "Lbrea" },
                { "Gosetsu", "Gever" },
                { "Yotsuyu", "Ygoeb" },
                { "Radovan", "Rvan" },
                { "Hraesvelgr", "Hralgr" },
                { "Byregot", "Bgot" },
                { "Rhalgr", "Rhgr" },
                { "Azeyma", "Azma" },
                { "Nald'thal", "Nathal" },
                { "Menphina", "Mhina" },
                { "Halone", "Hone" },
                { "Nymeia", "Nmea" },
                { "Althyk", "Ahyk" },
                { "Nophica", "Nhica" },
                { "Thaliak", "Thaak" },
                { "Llymlaen", "Llaen" },
                { "Oschon", "Oson" },
                { "Eulogia", "Euia" }
            };

            _extrasVoiceList = new List<KeyValuePair<string, string>> {
                new KeyValuePair<string, string>("Tattooed Man", "Beggarly"),
                new KeyValuePair<string, string>("Storm Officer", "Beggarly"),
                new KeyValuePair<string, string>("Flame Sergeant", "Beggarly"),
                new KeyValuePair<string, string>("Traitorous Flame Soldier", "Beggarly"),
                new KeyValuePair<string, string>("Riol", "Mciv"),
                new KeyValuePair<string, string>("Titan", "Rava"),
                new KeyValuePair<string, string>("Ramuh", "Rava"),
                new KeyValuePair<string, string>("Garuda", "Hyn"),
                new KeyValuePair<string, string>("Baderon", "Mciv"),
                new KeyValuePair<string, string>("Frixio", "Moya"),
                new KeyValuePair<string, string>("Raya-O-Senna", "Kes"),
                new KeyValuePair<string, string>("Livia sas Junius", "Ygoeb"),
                new KeyValuePair<string, string>("Teledji Adeledji", "Lito"),
                new KeyValuePair<string, string>("Nabriales", "Lbrea"),
                new KeyValuePair<string, string>("Mogloo", "Beggarly")
            };

            _echoValuesList = new List<KeyValuePair<string, bool>> {
                new KeyValuePair<string, bool>("Gaius van Baelsar", true),
                new KeyValuePair<string, bool>("Hades", true),
                new KeyValuePair<string, bool>("Rhitahtyn sas Arvina", true),
                new KeyValuePair<string, bool>("Livia sas Junius", true),
                new KeyValuePair<string, bool>("King Thordan", true)
            };

            _pitchValuesList = new List<KeyValuePair<string, float>> {
                new KeyValuePair<string, float>("Gaius van Baelsar", 0.9f),
                new KeyValuePair<string, float>("Rhitahtyn sas Arvina", 0.9f),
                new KeyValuePair<string, float>("Livia sas Junius", 0.9f),
                new KeyValuePair<string, float>("Frixio", 1.1f),
                new KeyValuePair<string, float>("Raya-O-Senna", 1.05f),
                new KeyValuePair<string, float>("Teledji Adeledji", 1.1f),
                new KeyValuePair<string, float>("Titan", 0.8f),
                new KeyValuePair<string, float>("Ramuh", 0.9f),
                new KeyValuePair<string, float>("Hraesvelgr", 0.8f),
                new KeyValuePair<string, float>("Hades", 0.9f),
                new KeyValuePair<string, float>("Moenbryda", 0.9f),
                new KeyValuePair<string, float>("Nabriales", 1.05f),
                new KeyValuePair<string, float>("King Thordan", 0.9f)
            };
        }

        public Dictionary<string, string> CharacterToVoiceList { get => _characterToVoiceList; set => _characterToVoiceList = value; }
        public Dictionary<string, List<string>> NameAndAliasesList { get => _nameAndAliasesList; set => _nameAndAliasesList = value; }
        public List<KeyValuePair<string, string>> ExtrasVoiceList { get => _extrasVoiceList; set => _extrasVoiceList = value; }
        public List<KeyValuePair<string, bool>> EchoValuesList { get => _echoValuesList; set => _echoValuesList = value; }
        public List<KeyValuePair<string, float>> PitchValuesList { get => _pitchValuesList; set => _pitchValuesList = value; }
    }
}
